class Constants:
    BASE_WIDTH, BASE_HEIGHT = 10, 6
    MULTIPLICATOR_WIDTH, MULTIPLICATOR_HEIGHT = 100, 100
    WINDOW_WIDTH, WINDOW_HEIGHT = int(MULTIPLICATOR_WIDTH * BASE_WIDTH), int(MULTIPLICATOR_HEIGHT * BASE_HEIGHT)

    NUMBER_OF_HORIZONTAL_BIG_PIXELS = WINDOW_WIDTH

    MINIMAP_BASE = 3
    MULTIPLICATOR_MINIMAP = 10 * MINIMAP_BASE
    MULTIPLICATOR_MINIMAP_HALF = int(MULTIPLICATOR_MINIMAP / 2)
    MIN_DELTA_POSITION = 0.1
    MIN_DELTA_POSITION_DOUBLE = MIN_DELTA_POSITION * 2
    MIN_DELTA_ANGLE = 5
    MAP_HALF_COORDINATE = 0.5

    COLOR_WHITE = (255, 255, 255)
    COLOR_BLACK = (0, 0, 0)
    COLOR_CYAN = (0, 255, 255)
    COLOR_GREEN = (0, 255, 0)
    COLOR_RED = (255, 0, 0)
    COLOR_GRAY = (50, 50, 50)
    COLOR_LIGHT_GRAY = (125, 125, 125)
    COLOR_YELLOW = (255, 255, 0)
    COLOR_BLUE = (0, 0, 255)
